# Generated by Django 4.1.4 on 2022-12-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrinhoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=150)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('senha_cliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=150)),
                ('descricao_plano', models.TextField()),
                ('valor_plano', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_postagem', models.CharField(max_length=150)),
                ('auto_postagem', models.CharField(max_length=100)),
                ('data_postagem', models.DateField(auto_now=True)),
                ('descricao_postagem', models.TextField()),
                ('imagem_postagem', models.ImageField(upload_to='postagens/')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=150)),
                ('peso_produto', models.CharField(max_length=100)),
                ('marca_produto', models.CharField(max_length=100)),
                ('descricao_produto', models.TextField()),
                ('imagem_produto', models.ImageField(upload_to='produtos/')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=150)),
                ('descricao_sevico', models.TextField()),
                ('imagem_servico', models.ImageField(upload_to='servico/')),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_treinador', models.CharField(max_length=150)),
                ('email_treinador', models.EmailField(max_length=254)),
                ('telefone_treinador', models.CharField(max_length=100)),
                ('especializacao_treinador', models.CharField(max_length=100)),
                ('imagem_treinador', models.ImageField(upload_to='treinadores/')),
                ('link_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('link_linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('link_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('link_pinterest', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
