# Generated by Django 4.1.4 on 2022-12-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name_plural': 'Postagens'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='treinador',
            options={'verbose_name_plural': 'Treinadores'},
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='auto_postagem',
        ),
        migrations.AddField(
            model_name='postagem',
            name='autor_postagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.treinador'),
            preserve_default=False,
        ),
    ]
